# Generated by Django 3.0.1 on 2019-12-20 17:06

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20190820_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewpost',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
